/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package poster.scan;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import org.apache.commons.configuration2.EnvironmentConfiguration;
import org.apache.commons.io.FileUtils;
import org.json.JSONArray;
import org.json.JSONObject;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.http.HttpClient;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Base64;
import java.util.List;

public class App {
    String instagram_username = "d3artswestwood";
    public void collectImages(Integer numberOfImages) {
        GalleryDL gallerydl = GalleryDL.newBuilder()
                .setExecPath("/opt/homebrew/bin/gallery-dl")
                .excludeVideos()
                .limitMaxPosts(numberOfImages)
                .addUrl("https://www.instagram.com/"+instagram_username+"/")
                .build();
        gallerydl.run();
        Mogrify mogrify = Mogrify.newBuilder()
                .setExecPath("/opt/homebrew/bin/mogrify")
                .setImageSize(150, 150)
                .setPhotoPath(System.getProperty("java.io.tmpdir") + "/instagram/"+instagram_username)
                .setTargetExtension("jpg")
                .build();
        mogrify.run();
    }
    public List<JSONObject> processImages() throws IOException {
        File[] imageFiles = getFiles();
        URL url = new URL("https://api.openai.com/v1/chat/completions");
        List<JSONObject> showData = new ArrayList<>();

        if (imageFiles != null) {
            System.out.println("Querying Open AI");
            for (File file : imageFiles) {
                byte[] imageContent = FileUtils.readFileToByteArray(file);
                String encodedImage = Base64.getEncoder().encodeToString(imageContent);

                JSONObject jsonQuery = new JSONObject()
                        .put("model", "gpt-4o-mini")
                        .put("messages", new JSONArray()
                                .put(new JSONObject()
                                        .put("role", "user")
                                        .put("content", new JSONArray()
                                                .put(new JSONObject()
                                                        .put("type", "text")
                                                        .put("text", "{\n" +
                                                                "    \"date\": \"2023-10-25\",\n" +
                                                                "    \"venue\": {\n" +
                                                                "        \"db_name\": \"d3_arts\",\n" +
                                                                "        \"stylized_name\": \"D3 Arts\",\n" +
                                                                "        \"address_protected\": false,\n" +
                                                                "        \"address\": \"3632 Morrison Road\",\n" +
                                                                "        \"website\": \"d3arts.org\"\n" +
                                                                "    },\n" +
                                                                "    \"cost\": \"0.00\",\n" +
                                                                "    \"doors_time\": \"17:00:00\",\n" +
                                                                "    \"show_start_time\": \"17:00:00\",\n" +
                                                                "    \"age_requirement\": 0,\n" +
                                                                "    \"description\": \"\",\n" +
                                                                "    \"title\": null,\n" +
                                                                "    \"bands\": [\n" +
                                                                "        {\n" +
                                                                "            \"db_name\": \"jazz_morillo\",\n" +
                                                                "            \"stylized_name\": \"Jazz Morillo\",\n" +
                                                                "            \"genre\": \"rock\",\n" +
                                                                "            \"biography\": \"Jazz morillo is a great singer, how awesome\",\n" +
                                                                "            \"website\": \"jazzmorillo.com\",\n" +
                                                                "            \"music_link\": \"spotify.com/jazz_morillo\",\n" +
                                                                "            \"contact_email\": \"jazzmorillo@gmail.com\",\n" +
                                                                "            \"instagram_username\": \"@jazzmorillo\",\n" +
                                                                "            \"twitter_username\": \"@jazzmorillo\",\n" +
                                                                "            \"tiktok_username\": \"@jazzmorillo\",\n" +
                                                                "            \"is_active\": true\n" +
                                                                "        }\n" +
                                                                "    ]\n" +
                                                                "}\n" +
                                                                "\n" +
                                                                "Based on this concert poster can you find information like that provided in the example json, and\n" +
                                                                "return it in an identical structure. I'll break down each parameter so its easier for you to find.\n" +
                                                                "\n" +
                                                                "Example JSON\n" +
                                                                "{\n" +
                                                                "    \"date\": \"2023-10-25\",\n" +
                                                                "    \"venue\": {\n" +
                                                                "        \"db_name\": \"d3_arts\",\n" +
                                                                "        \"stylized_name\": \"D3 Arts\",\n" +
                                                                "        \"address_protected\": false,\n" +
                                                                "        \"address\": \"3632 Morrison Road\",\n" +
                                                                "        \"website\": \"d3arts.org\"\n" +
                                                                "    },\n" +
                                                                "    \"cost\": \"0.00\",\n" +
                                                                "    \"doors_time\": \"17:00:00\",\n" +
                                                                "    \"show_start_time\": \"17:00:00\",\n" +
                                                                "    \"age_requirement\": 0,\n" +
                                                                "    \"description\": \"\",\n" +
                                                                "    \"title\": \"\",\n" +
                                                                "    \"bands\": [\n" +
                                                                "        {\n" +
                                                                "            \"db_name\": \"example_band\",\n" +
                                                                "            \"stylized_name\": \"Example Band\",\n" +
                                                                "            \"genre\": \"rock\",\n" +
                                                                "            \"biography\": \"Example Band is a great singer, how awesome\",\n" +
                                                                "            \"website\": \"exampleband.com\",\n" +
                                                                "            \"music_link\": \"spotify.com/example_band\",\n" +
                                                                "            \"contact_email\": \"examplebadn@gmail.com\",\n" +
                                                                "            \"instagram_username\": \"@exampleband\",\n" +
                                                                "            \"twitter_username\": \"@exampleband\",\n" +
                                                                "            \"tiktok_username\": \"@exampleband\",\n" +
                                                                "            \"is_active\": true\n" +
                                                                "        }\n" +
                                                                "    ]\n" +
                                                                "}\n" +
                                                                "\n" +
                                                                "\"date\" is the date of the event\n" +
                                                                "\"venue\" is a json object that contains data about the venue the show is being played at. It contains \n" +
                                                                "these keys.\n" +
                                                                "    {\n" +
                                                                "    \"db_name\" the name of the venue in a format without spaces and lowercase\n" +
                                                                "        \"stylized_name\" the name of the venue as found on the poster\n" +
                                                                "        \"address_protected\" a boolean representing whether or not the address is publicly available. If the poster says \"DM for address\" it is likely not publically available. true means the address is not publicly available,\n" +
                                                                "    false means it is\n" +
                                                                "        \"address\" the address of the venue\n" +
                                                                "        \"website\" the venues website\n" +
                                                                "}\n" +
                                                                "\"cost\" is a number representing how much the event costs, if its not listed, assume 0\n" +
                                                                "\"doors_time\" is the time doors open, it should be around a part of the poster that says doors\n" +
                                                                "\"show_start_time\" is the time the show starts. if there's only one time on the poster, its likely this one. If there are two, it will be the later one\n" +
                                                                "\"age_requirement\" is how old you have to be to get into the event it should be encoded as such (all ages/not listed -> 0,\n" +
                                                                "16+ -> 16,\n" +
                                                                "18+ -> 18,\n" +
                                                                "21+ -> 21)\n" +
                                                                "\"description\" a description or tagline of the event if provided\n" +
                                                                "\"title\" the name of the event if provided\n" +
                                                                "\"bands\" is a json array containing an object for each band playing the show. The band object has these keys, and there are likely going to be multiple bands.\n" +
                                                                "    {\n" +
                                                                "    \"db_name\" name of band without spaces and lowercase\n" +
                                                                "        \"stylized_name\" name of band as written on poster\n" +
                                                                "        \"genre\" genre of music that the band plays, for this parameter only it is ok to infer from the poster style. If that isn't possible and empty string is also fine\n" +
                                                                "        \"biography\" description of the band\n" +
                                                                "        \"website\" bands website\n" +
                                                                "        \"music_link\" a link pointing to where the bands music is (spotify, apple music, etc)\n" +
                                                                "        \"contact_email\" an email to contact the band, if its not close the band name, its likely another email and should not be inputted here\n" +
                                                                "        \"instagram_username\" the bands instagram username\n" +
                                                                "        \"twitter_username\" the bands twitter username\n" +
                                                                "        \"tiktok_username\" the bands tiktok username\n" +
                                                                "        \"is_active\" whether the band is still playing shows\n" +
                                                                "}\n" +
                                                                "\n" +
                                                                "This is an ambitious task so if certain data points aren't available, its acceptable to leave them blank (empty strings for strings and 0s for numbers),\n" +
                                                                "just make sure the structure is identical to the input. If the image appears to not be a concert poster,\n" +
                                                                "just return an empty json. And in your response, only print the json. Thank you!")
                                                )
                                                .put(new JSONObject()
                                                        .put("type", "image_url")
                                                        .put("image_url", new JSONObject()
                                                                .put("url", "data:image/jpeg;base64," + encodedImage)
                                                        )
                                                )
                                        )
                                )
                        )
                        .put("max_tokens", 5000);
                String query = jsonQuery.toString();
                HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                connection.setRequestMethod("POST");
                connection.setDoOutput(true);
                connection.setRequestProperty("Content-Type", "application/json");
                connection.setRequestProperty("Authorization", "Bearer " + System.getenv("OPENAI_API_KEY"));
                connection.setRequestProperty("Content-Length", Integer.toString(query.length()));
                connection.getOutputStream().write(query.getBytes(StandardCharsets.UTF_8));
                connection.connect();

                // https://stackoverflow.com/a/59997267
                JSONObject jsonResponse = getJsonObject(connection);
                String stringShowResponse = (String) jsonResponse.getJSONArray("choices").getJSONObject(0).getJSONObject("message").get("content");

                JSONObject showResponse = new JSONObject(stringShowResponse.substring(8, stringShowResponse.length()-3));
                if (!showResponse.isEmpty()) {
                    showData.add(showResponse);
                }
            }
        }
        System.out.println(showData);
        return showData;
    }

    private static JSONObject getJsonObject(HttpURLConnection connection) throws IOException {
        BufferedReader br = null;
        StringBuffer response = new StringBuffer();
        if (connection.getResponseCode() == 200) {
            br = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String strCurrentLine;
            while ((strCurrentLine = br.readLine()) != null) {
                response.append(strCurrentLine);
            }
        } else {
            br = new BufferedReader(new InputStreamReader(connection.getErrorStream()));
            String strCurrentLine;
            while ((strCurrentLine = br.readLine()) != null) {
                response.append(strCurrentLine);
            }
        }
        JSONObject jsonResponse = new JSONObject(response.toString());
        return jsonResponse;
    }

    private File[] getFiles() {
        EnvironmentConfiguration config = new EnvironmentConfiguration();
        String image_path = System.getProperty("java.io.tmpdir") + "/instagram/" + instagram_username;
        File directory = new File(image_path);
        FilenameFilter imageFilter = (dir, name) -> {
            String lowercaseName = name.toLowerCase();
            return lowercaseName.endsWith(".jpg") || lowercaseName.endsWith(".jpeg") ||
                    lowercaseName.endsWith(".png");
        };
        File[] imageFiles = directory.listFiles(imageFilter);
        return imageFiles;
    }

    public Integer apiPost(List<JSONObject> showData) throws JsonProcessingException {
        for (JSONObject event: showData) {
            Venue venue = new Venue(event.getJSONObject("venue"));
            String venueForeign = venue.getDBName();
            try {
                venue.postData();
            } catch (Exception e) {
                e.printStackTrace();
            }

            JSONArray bands = event.getJSONArray("bands");
            List<String> bandForeign = new ArrayList<>();
            for (int i = 0; i < bands.length(); i++) {
                JSONObject jsonBand = (JSONObject) bands.get(i);
                Band band = new Band(jsonBand);
                bandForeign.add(band.getDBName());
                try {
                    band.postData();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            JSONObject showJSON = new JSONObject(event.toString());
            showJSON.remove("venue");
            showJSON.remove("bands");
            showJSON.put("venue", venueForeign);
            showJSON.put("bands", bandForeign);
            Show show = new Show(showJSON);
            try {
                show.postData();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return 200;
    }
    public static void main(String[] args) throws IOException {
        App app = new App();
        System.out.println("Collecting Images");
        app.collectImages(25);
        System.out.println("Processing Images");
        app.apiPost(app.processImages());
    }
}
